#!/bin/bash

# Script para inicializar el despliegue de LyVenTum
# Ejecuta este script desde la carpeta del proyecto

echo "🚀 Iniciando configuración de LyVenTum..."

# 1. Asegurar que estamos en el directorio correcto
# (El usuario ya debe haber navegado aquí, pero confirmamos el path actual para log)
CURRENT_PATH=$(pwd)
echo "📂 Directorio actual: $CURRENT_PATH"

# 2. Inicializar Git
if [ -d ".git" ]; then
    echo "ℹ️  Git ya está inicializado."
else
    echo "git init..."
    git init
    echo "✅ Git inicializado."
fi

# 3. Ignorar archivos innecesarios (crear .gitignore si no existe)
if [ ! -f ".gitignore" ]; then
    echo "📝 Creando .gitignore estándar..."
    cat > .gitignore << EOL
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_flat/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your build tool generates a public directory.
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Valid local envs
.env.local
.env.development.local
.env.test.local
.env.production.local

# macOS
.DS_Store
EOL
    echo "✅ .gitignore creado."
fi

# 4. Agregar archivos
echo "📦 Agregando archivos a Git..."
git add .

# 5. Crear commit inicial
echo "💾 Creando commit inicial..."
git commit -m "chore: initial commit - soft launch ready"

# 6. Renombrar rama a main
git branch -M main

echo "---------------------------------------------------"
echo "🎉 ¡LISTO! El repositorio local está configurado."
echo ""
echo "Siguientes pasos:"
echo "1. Ve a https://vercel.com/new"
echo "2. Conecta tu cuenta de GitHub/GitLab/Bitbucket (si vas a usar repo remoto)"
echo "   O usa 'vercel deploy' en esta terminal si tienes Vercel CLI instalado."
echo ""
echo "Para subir a GitHub (opcional pero recomendado):"
echo "  git remote add origin <TU_URL_DE_GITHUB>"
echo "  git push -u origin main"
echo "---------------------------------------------------"
